spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
